#!/usr/bin/env python
"""Paper-ready LaTeX tables for the refined ID space (latent refiner).

    python -m scripts.make_latent_tables [--out tables/latent_refined_space.tex]

Two tables, both generated from artefacts rather than transcribed:

TABLE 1  the refined space's GEOMETRY, from the `*.stats.json` files written by
         scripts/train_latent_refiner.py (weight sweep, job 10524127). This is
         the complete result: how far N_z can be moved from N_emb, and at what
         cost to the latent's item-level detail.

TABLE 2  DOWNSTREAM unlearning, from the run logs via
         scripts.extract_latent_arms. Restricted to the panel that is actually
         replicated (mid, lambda_f=0.1, lambda_n=0.01, seeds 2/3/5) -- the other
         panels are single-seed and are not paper material.

Numbers are read from disk on every run, so a re-generated table can never drift
from the runs it claims to describe.
"""

from __future__ import annotations

import argparse
import glob
import json
import os
import re
import sys
from typing import Dict, List

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from scripts.extract_latent_arms import (  # noqa: E402
    CLEAN_NDCG10_BEAUTY_W256, SH_REF, collect,
)

HDR = "% Generated by scripts/make_latent_tables.py -- do not edit by hand.\n"

# Readable names for the sweep configs, in reporting order (most-diverged first).
SWEEP_ORDER = ["rec_light", "sid_dom", "nbr_off", "nbr_down", "sid_up",
               "baseline", "sid_off"]

# Every row needs a name in the RENDERED table. Identifying a row by its weight
# triple alone makes the reader decode numbers, and a trailing "% default"
# LaTeX comment is invisible in the output.
SWEEP_LABEL = {
    "rec_light": "recon-light",
    "sid_dom":   "SID-dominant",
    "nbr_off":   "refined (ours)",
    "nbr_down":  "align-damped",
    "sid_up":    "SID-balanced",
    "baseline":  "default (shipped)",
    "sid_off":   "control, $w_{\\text{sid}}{=}0$",
}


def _agg(vals: List[float], nd: int) -> str:
    if not vals:
        return "--"
    mean = sum(vals) / len(vals)
    if len(vals) == 1:
        return f"{mean:.{nd}f}"
    half = (max(vals) - min(vals)) / 2
    return f"{mean:.{nd}f}\\,$\\pm$\\,{half:.{nd}f}"


def table_geometry(sweep_root: str) -> str:
    rows: Dict[str, Dict] = {}
    for p in glob.glob(os.path.join(sweep_root, "*.stats.json")):
        m = re.search(r"tgtmid_(\w+?)_dz", os.path.basename(p))
        if not m:
            continue
        d = json.load(open(p))
        c, g = d["config"], d["diagnostics"]
        rows[m.group(1)] = {
            "wr": c["w_reconstruction"], "wn": c["w_neighborhood"],
            "ws": c["w_sid_consistency"],
            "ov": g["latent_vs_embedding"]["mean_overlap_at_k"],
            "dj": g["latent_vs_embedding"]["frac_disjoint"],
            "pf": g["prefix_sample"]["mean_prefix_recovered_by_latent"],
            "pe": g["prefix_sample"]["mean_prefix_recovered_by_embedding"],
            "rec": d["training"]["final"].get("rec", float("nan")),
        }
    if not rows:
        raise SystemExit(f"no *.stats.json under {sweep_root!r}")
    pe = next(iter(rows.values()))["pe"]

    L = [HDR, "\\begin{table}[t]", "\\centering", "\\small",
         "\\caption{Geometry of the refined ID space (Beauty, $K{=}256$, "
         "12{,}101 items, $k{=}8$; the \\emph{mid} poisoned model). "
         "The refiner maps each item to "
         "$z_i=\\mathrm{MLP}([\\mathrm{SIDEmb}(i), x_i])$, where $x_i$ is the "
         "pre-quantization embedding, and is trained with "
         "$\\mathcal{L}=w_{\\text{rec}}\\mathcal{L}_{\\text{rec}}"
         "+w_{\\text{align}}\\mathcal{L}_{\\text{align}}"
         "+w_{\\text{sid}}\\mathcal{L}_{\\text{sid}}$: "
         "$\\mathcal{L}_{\\text{rec}}$ reconstructs $x_i$ from $z_i$, "
         "$\\mathcal{L}_{\\text{align}}$ is an InfoNCE pulling each item's "
         "top-$k$ neighbours in $x$-space together in $z$, and "
         "$\\mathcal{L}_{\\text{sid}}$ an InfoNCE over items sharing an SID "
         "prefix. $\\mathcal{N}_z$ / $\\mathcal{N}_{\\text{emb}}$ denote the "
         "top-$k$ cosine neighbourhood in $z$ / in $x$. Columns: "
         "\\emph{overlap} $=|\\mathcal{N}_z\\cap\\mathcal{N}_{\\text{emb}}|/k$; "
         "\\emph{disj.} $=$ share of items whose two neighbourhoods are "
         "disjoint; \\emph{SID rec.} $=$ share of an item\'s shared-prefix "
         "neighbourhood the space recovers "
         f"($\\mathcal{{N}}_{{\\text{{emb}}}}$ scores {pe:.3f}); "
         "$\\mathcal{L}_{\\text{rec}}$ $=$ final reconstruction error, i.e.\\ "
         "how much item-level detail $z$ retains. "
         "Lowering $w_{\\text{align}}$ and raising $w_{\\text{sid}}$ moves "
         "$\\mathcal{N}_z$ away from $\\mathcal{N}_{\\text{emb}}$ at "
         "essentially no cost in $\\mathcal{L}_{\\text{rec}}$. One seed per "
         "row; the last two rows are the shipped default and the "
         "$w_{\\text{sid}}{=}0$ ablation that isolates the SID term. NOTE: $w_{\\text{align}}$ is a REFINER training weight (code knob \\texttt{w\\_neighborhood}) and is unrelated to $\\lambda_n$ in Tab.~\\ref{tab:latent-unlearn}, which weights the coherence term of the UNLEARNING objective. $w_{\\text{align}}{=}0$ disables no unlearning term.}",
         "\\label{tab:latent-geometry}",
         "\\begin{tabular}{lrrrrrrr}", "\\toprule",
         "setting & $w_{\\text{rec}}$ & $w_{\\text{align}}$ & $w_{\\text{sid}}$ & "
         "overlap $\\downarrow$ & disj. $\\uparrow$ & SID rec. $\\uparrow$ & "
         "$\\mathcal{L}_{\\text{rec}}$ $\\downarrow$ \\\\", "\\midrule"]
    for name in SWEEP_ORDER:
        r = rows.get(name)
        if r is None:
            continue
        # nbr_off is the configuration adopted for the downstream runs; bold it.
        bold = name == "nbr_off"
        cells = [SWEEP_LABEL.get(name, name),
                 f"{r['wr']:.1f}", f"{r['wn']:.1f}", f"{r['ws']:.1f}",
                 f"{r['ov']:.3f}", f"{100 * r['dj']:.1f}\\%",
                 f"{r['pf']:.3f}", f"{r['rec']:.3f}"]
        if bold:
            cells = [f"\\textbf{{{c}}}" for c in cells]
        # Rule above the two reference rows, so "default" and "control" read as
        # the baseline block rather than as more sweep points.
        if name == "baseline":
            L.append("\\midrule")
        L.append(" & ".join(cells) + " \\\\")
    L += ["\\bottomrule", "\\end{tabular}", "\\end{table}", ""]
    return "\n".join(L)


def table_downstream(runs_dir: str, logs_dir: str, omit_pending: bool = False) -> str:
    """Table 2: is a refined neighbourhood worth it, versus the state before?

    Two blocks. The first is what existed BEFORE any of this: no coherence term
    at all, the shipped `prefix` neighbourhood, and the `embedding` top-k. The
    second is the refined space. Delta columns are taken against `embedding`, the
    incumbent the refined space would have to displace, so "worth it" is a
    property you can read off a row rather than compute.
    """
    rows = collect(runs_dir, logs_dir)
    sh_p, sh_c = SH_REF["mid"]
    gap = sh_p - sh_c

    BEFORE = [("", "0.0", "no $\\mathcal{L}_n$ ($\\lambda_n{=}0$)"),
              ("prefix", "0.01", "$\\mathcal{N}_{\\text{prefix}}$ (shipped default)"),
              ("embedding", "0.01", "$\\mathcal{N}_{\\text{emb}}$ (incumbent)")]
    AFTER = [("latent", "0.01", "$\\mathcal{N}_z$, overlap 0.78"),
             ("latent_zlow", "0.01", "$\\mathcal{N}_z$, overlap 0.42"),
             ("emblatent_matched", "0.01",
              "$\\mathcal{N}_{\\text{emb}}\\cup\\mathcal{N}_z$")]

    def pick(meth, ln):
        return [r for r in rows if r["strat"] == "mid" and r["lf"] == "0.1"
                and r["ls"] == "0.1" and r["ln"] == ln and r["method"] == meth
                and r["sh10"] is not None and r["ndcg10"] is not None]

    def stats(rs):
        pgr = [(sh_p - r["sh10"]) / gap for r in rs]
        ur = [r["ndcg10"] / CLEAN_NDCG10_BEAUTY_W256 for r in rs]
        return (sum(pgr) / len(pgr), sum(ur) / len(ur))

    ref = pick("embedding", "0.01")
    ref_pgr, ref_ur = stats(ref) if ref else (None, None)

    def emit(meth, ln, label, deltas):
        rs = pick(meth, ln)
        if not rs:
            if omit_pending:
                return None
            return (f"{label} & -- & \\multicolumn{{5}}{{c}}{{\\emph{{pending}}}} \\\\")
        sh = _agg([r["sh10"] for r in rs], 5)
        pgr_v = [(sh_p - r["sh10"]) / gap for r in rs]
        ur_v = [r["ndcg10"] / CLEAN_NDCG10_BEAUTY_W256 for r in rs]
        cells = [label, str(len(rs)), sh, "$+$" + _agg(pgr_v, 3), _agg(ur_v, 3)]
        if not deltas or ref_pgr is None:
            cells += ["--", "--"]
        else:
            dp = sum(pgr_v) / len(pgr_v) - ref_pgr
            du = sum(ur_v) / len(ur_v) - ref_ur
            cells += [f"${dp:+.3f}$", f"${du:+.3f}$"]
        return " & ".join(cells) + " \\\\"

    L = [HDR, "\\begin{table}[t]", "\\centering", "\\small",
         "\\caption{Is a refined neighbourhood worth it? Spam unlearning on "
         "Beauty (TIGER, bandwagon 1\\%, $n_{\\text{target}}{=}1$, "
         "\\emph{mid} target; $\\lambda_f{=}\\lambda_s{=}0.1$, "
         "$\\lambda_n{=}0.01$), mean\\,$\\pm$\\,half-range over unlearning "
         "seeds $\\{2,3,5\\}$. Every $\\mathcal{N}_z$ row USES the coherence term ($\\lambda_n{=}0.01$); the refined space enters only through $\\mathcal{L}_n$. "
         "\\textbf{Upper block} is the state before this work: the shipped "
         "shared-SID-prefix neighbourhood and the pre-quantization top-$k$. "
         "The $\\lambda_n{=}0$ row is not a competing neighbourhood -- $z$ is "
         "read only when $\\lambda_n\\neq0$, so $\\mathcal{N}_z$ does not "
         "exist there. It instead BOUNDS what any neighbourhood can be worth: "
         "the whole $\\mathcal{L}_n$ mechanism spans PGR $+0.970$ to $+0.987$, "
         "so the choice of neighbourhood competes for a share of $0.017$. \\textbf{Lower block} is the refined space "
         "$z_i=\\mathrm{MLP}([\\mathrm{SIDEmb}(i),x_i])$ at two settings of its "
         "training weights (Tab.~\\ref{tab:latent-geometry}), and the union. "
         "$\\Delta$ columns are against $\\mathcal{N}_{\\text{emb}}$, the "
         "incumbent: a variant is worth adopting only if $\\Delta$PGR $>0$ without "
         "a loss in UR. "
         "SH@10 (spam-hit rate) is the fraction of evaluation examples whose "
         "ground-truth label is not itself a deletion target but whose top-10 "
         "contains one; lower is better. "
         "UR $=$ N@10\\,/\\,N@10$_{\\text{clean}}$ "
         f"(N@10$_{{\\text{{clean}}}}={CLEAN_NDCG10_BEAUTY_W256:.5f}$); PGR $=$ "
         "$(\\text{SH}_{\\text{poison}}{-}\\text{SH})/"
         "(\\text{SH}_{\\text{poison}}{-}\\text{SH}_{\\text{clean}})$ with "
         f"$\\text{{SH}}_{{\\text{{poison}}}}={sh_p:.5f}$, "
         f"$\\text{{SH}}_{{\\text{{clean}}}}={sh_c:.5f}$; PGR $=1$ means spam "
         "exposure was pushed all the way down to the clean model. "
         "\\emph{mid} is the only target with residual exposure once "
         "$\\mathcal{L}_F$ has acted; on \\emph{unpopular} and "
         "\\emph{popular} PGR saturates at $+1.000$ for every arm, so no "
         "neighbourhood is distinguishable there.}",
         "\\label{tab:latent-unlearn}",
         "\\begin{tabular}{lccccrr}", "\\toprule",
         "$\\mathcal{L}_n$ neighbourhood & seeds & SH@10 $\\downarrow$ & "
         "PGR@10 $\\uparrow$ & UR $\\uparrow$ & $\\Delta$PGR & $\\Delta$UR \\\\",
         "\\midrule",
         "\\multicolumn{7}{l}{\\textit{no neighbourhood term (bounds the rest)}} \\\\"]
    _r = emit(*BEFORE[0], deltas=True)
    if _r: L.append(_r)
    L += ["\\midrule",
          "\\multicolumn{7}{l}{\\textit{neighbourhood sources before this work}} \\\\"]
    for meth, ln, label in BEFORE[1:]:
        _r = emit(meth, ln, label, deltas=(meth != "embedding"))
        if _r: L.append(_r)
    L += ["\\midrule",
          "\\multicolumn{7}{l}{\\textit{refined ID space (this work)}} \\\\"]
    for meth, ln, label in AFTER:
        _r = emit(meth, ln, label, deltas=True)
        if _r: L.append(_r)
    L += ["\\bottomrule", "\\end{tabular}", "\\end{table}", ""]
    return "\n".join(L)


def table_headroom(runs_dir: str, logs_dir: str, omit_pending: bool = False) -> str:
    """Table 3: L_n's value is a function of the operating point, not a constant.

    At the selected lambda_f=0.1 the forget term alone already removes ~97% of the
    poisoning gap, so L_n has almost nothing left to do and no neighbourhood can
    be told from another. Lowering lambda_f re-opens the gap and the neighbourhood
    term becomes the dominant removal mechanism. Reporting only the saturated
    point would have made L_n look worthless.
    """
    rows = collect(runs_dir, logs_dir)
    sh_p, sh_c = SH_REF["mid"]
    gap = sh_p - sh_c
    ARMS = [("", "no $\\mathcal{L}_n$"),
            ("embedding", "$\\mathcal{N}_{\\text{emb}}$"),
            ("latent", "$\\mathcal{N}_z$ (0.78)"),
            ("latent_zlow", "$\\mathcal{N}_z$ (0.42)")]
    PANELS = [("0.01", "0.1"), ("0.03", "0.1"), ("0.1", "0.01")]

    L = [HDR, "\\begin{table}[t]", "\\centering", "\\small",
         "\\caption{The value of the coherence term depends on the operating "
         "point (Beauty, TIGER, \\emph{mid} target, $\\lambda_s{=}0.1$). "
         "At the selected $\\lambda_f{=}0.1$ the forget term alone already "
         "reaches PGR $+0.970$, leaving $\\mathcal{L}_n$ almost nothing to "
         "recover and no neighbourhood source distinguishable. Lowering "
         "$\\lambda_f$ re-opens the gap -- at $\\lambda_f{=}0.01$ the forget "
         "term recovers less than half of it -- and every neighbourhood then "
         "closes it almost completely, at a cost of roughly 3 UR points. "
         "NOTE the $\\lambda_f{\\in}\\{0.01,0.03\\}$ panels use "
         "$\\lambda_n{=}0.1$ and the $\\lambda_f{=}0.1$ panel "
         "$\\lambda_n{=}0.01$, each the better value at that setting; rows are "
         "comparable WITHIN a panel. $n$ is the number of unlearning seeds.}",
         "\\label{tab:latent-headroom}",
         "\\begin{tabular}{lcccc}", "\\toprule",
         "$\\mathcal{L}_n$ neighbourhood & $n$ & SH@10 $\\downarrow$ & "
         "PGR@10 $\\uparrow$ & UR $\\uparrow$ \\\\"]
    for lf, ln in PANELS:
        blk = []
        for meth, label in ARMS:
            want = "0.0" if meth == "" else ln
            rs = [r for r in rows if r["strat"] == "mid" and r["lf"] == lf
                  and r["ls"] == "0.1" and r["ln"] == want and r["method"] == meth
                  and r["sh10"] is not None and r["ndcg10"] is not None]
            if not rs:
                if not omit_pending:
                    blk.append(f"{label} & -- & \\multicolumn{{3}}{{c}}{{\\emph{{pending}}}} \\\\")
                continue
            pgr = [(sh_p - r["sh10"]) / gap for r in rs]
            ur = [r["ndcg10"] / CLEAN_NDCG10_BEAUTY_W256 for r in rs]
            blk.append(f"{label} & {len(rs)} & {_agg([r['sh10'] for r in rs], 5)} & "
                       f"$+${_agg(pgr, 3)} & {_agg(ur, 3)} \\\\")
        if not blk:
            continue
        L.append("\\midrule")
        L.append(f"\\multicolumn{{5}}{{l}}{{\\textit{{$\\lambda_f={lf}$, "
                 f"$\\lambda_n={ln}$}}}} \\\\")
        L += blk
    L += ["\\bottomrule", "\\end{tabular}", "\\end{table}", ""]
    return "\n".join(L)


def main(argv: List[str] | None = None) -> int:
    p = argparse.ArgumentParser(description=__doc__,
                                formatter_class=argparse.RawDescriptionHelpFormatter)
    p.add_argument("--sweep-root", default="embeddings/latent_sweep")
    p.add_argument("--runs-dir", default="logs/unlearn/runs")
    p.add_argument("--logs-dir", default="logs")
    p.add_argument("--out", default="tables/latent_refined_space.tex")
    p.add_argument("--omit-pending", action="store_true",
                   help="drop not-yet-run rows instead of printing 'pending'")
    a = p.parse_args(argv)

    body = (table_geometry(a.sweep_root) + "\n"
            + table_downstream(a.runs_dir, a.logs_dir, a.omit_pending) + "\n"
            + table_headroom(a.runs_dir, a.logs_dir, a.omit_pending))
    print(body)
    os.makedirs(os.path.dirname(os.path.abspath(a.out)) or ".", exist_ok=True)
    open(a.out, "w").write(body)
    print(f"% wrote {a.out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
